name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Build WASM
        working-directory: Chip8-web
        run: |
          emcc -O3 \
          main.c chip8.c \
          -s WASM=1 \
          -s USE_SDL=2 \
          --preload-file roms \
          -s "EXPORTED_FUNCTIONS=['_main', '_malloc', '_free', '_get_memory_buffer_ptr', '_get_register_v_value', '_get_program_counter', '_get_index_register', '_get_delay_timer_value', '_get_sound_timer_value', '_load_rom_from_file', '_set_key_state', '_set_emulator_paused', '_step_single_cycle', '_reset_emulator_state', '_get_available_theme_count', '_get_theme_name_at_index', '_set_active_theme']" \
          -s "EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap', 'FS', 'UTF8ToString']" \
          -o ../docs/chip8.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
